Repository linc-technologies/ember-spreadsheet-export, pull requests merged in 2024-10, with the labels that each got.

#36 feat: upgrades to `xlsx@^0.18.5`. (HERO-10268)
  package.json
  yarn.lock
Labels: hacktoberfest-accepted

#17 Remove initialize re-export
  app/services/csv.js
  app/services/excel.js
Labels: bug

#46 feat: upgrades to `xlsx@0.20.3` via CDN
  package.json
  yarn.lock
Labels: dependencies

#38 feat: upgrade to ember@4.4 (HERO-10268)
  .ember-cli
  .eslintignore
  .eslintrc.js
  .gitignore
  .npmignore
  .prettierignore
  CONTRIBUTING.md
  README.md
  config/ember-try.js
  package.json
  tests/dummy/app/index.html
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/helpers/.gitkeep
  tests/helpers/index.js
  tests/index.html
  yarn.lock
Labels: enhancement, dependencies

#39 feat: upgrades to `ember@4.8`. (HERO-10268)
  .github/workflows/pr.yml
  .github/workflows/release.yml
  README.md
  config/ember-try.js
  ember-cli-build.js
  package.json
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/environment.js
  yarn.lock
Labels: enhancement, dependencies

#40 feat: upgrades to `ember@4.12`. (HERO-10268)
  .ember-cli
  .eslintrc.js
  .npmignore
  .prettierrc.js
  .stylelintignore
  .stylelintrc.js
  README.md
  config/environment.js
  package.json
  tests/dummy/app/styles/app.css
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/dummy/config/environment.js
  vendor/.gitkeep
  yarn.lock
Labels: enhancement, dependencies

#42 feat: upgrades to `ember@5.8`. (HERO-10268)
  .eslintignore
  .npmignore
  CONTRIBUTING.md
  README.md
  package.json
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tsconfig.declarations.json
  yarn.lock
Labels: enhancement, dependencies

#43 feat: upgrades to `ember@5.12`. (HERO-10268)
  CONTRIBUTING.md
  README.md
  package.json
  tests/dummy/config/ember-cli-update.json
  tests/helpers/index.js
  yarn.lock
Labels: enhancement, dependencies
